services:
  # FastAPI Backend Service
  - type: web
    name: dv-atm-system
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MAX_ACCOUNTS
        value: 1000
      - key: MAX_TRANSACTION_AMOUNT
        value: 10000.0
      - key: LOG_LEVEL
        value: INFO
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Resource limits for free tier
    numInstances: 1
    
    # Custom domains (optional - you can add your own domain later)
    # customDomains:
    #   - name: your-domain.com
